# -*- coding: utf-8 -*-
"""NGC3_Annisa Triana Talmera

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pX1E8ZLV7HiIJqP5Z4rX_Sz3hBO7AWPh
"""

#Temperature Converter
print("NCG 2")
print("by Annisa Triana Talmera")
print("_________________________")

print("Hai, Caca!")

#Membuat fungsi Temperature

def convert_ck(c):          #Mengkonversikan Celcius ke Kelvin
    return 273.5 + c

def convert_cf (c):         #Mengkonversikan Celcius ke Fahrenheit
    return c * 9/5 + 32

def convert_kc (k):         #Mengkonversikan Kelvin ke Celcius
    return k - 273.15

def convert_fc (f):         #Mengkonversikan Fahrenheit ke Celcius
    return (f - 32) * 5/9

def convert_kf (k):         #Mengkonversikan Kelvin ke Fahrenheit
    return ((k-273.15)*9/5 +32)

def convert_fk (f):         #Mengkonversikan Fahrenheit ke Kelvin
    return ((f-32)*5/9 + 273.15)

#fungsi untuk input suhu
temp = input("Berapa nih suhu di sana? (eg; 32C, 42F, 60K):")
print(temp)
target_unit = input("Mau konvert kemana?: (C/F/K) ")
print(target_unit)
degree = int(temp[:-1])     #Ini biar yang diambil angkanya aja, kaya 32C, jadi ya cuma yang di variabel -1 nya doang yang diambil, cuma 32 nya aja biar bisa diitung lagi ke formula selanjutnya
unit = temp[-1]             #unit (angka yang bakal di convert) ini nih yang bakalan dioperasikan


#Pengoperasian suhu
if unit.upper()== "C":
    if target_unit.upper() == "K":
        result = round(convert_ck(degree),2)                      #Hasil dibulatkan 2 angka di belakang koma
        print("Konversi suhu di tempat kamu: ", result, " K")
    elif target_unit.upper() == "F":
        result = round(convert_cf(degree), 2)
        print("Konversi suhu di tempat kamu: ", result, "F")
    elif target_unit.upper() == "C":
        print("Lah mau ngekonversi apa? -_-")
    else: print("\nSuhu dimana tuh? Perasaan cuma ada C,F, dan K :)")

elif unit.upper() == "K":
    if target_unit.upper() == "C":
        result = round(convert_kc(degree),2)
        print("Konversi suhu di tempat kamu: ", result, " C")
    elif target_unit.upper() == "F":
        result = round(convert_kf(degree),2)
        print("Konversi suhu di tempat kamu: ", result, " F")
    elif target_unit.upper() == "C":
        print("Lah mau ngekonversi apa? -_-")
    else: print("\nSuhu dimana tuh? Perasaan cuma ada C,F, dan K :)")

elif unit.upper() == "F":
    if target_unit.upper() == "C":
        result = round(convert_fc(degree),2)
        print("Konversi suhu di tempat kamu: ", result, " C")
    elif target_unit.upper() == "K":
        result = round(convert_fk(degree),2)
        print("Konversi suhu di tempat kamu: ", result, " K")
    elif target_unit.upper() == "F":
        print("Lah mau ngekonversi apa? -_-")
    else: print("\nSuhu dimana tuh? Perasaan cuma ada C,F, dan K :)")
else: print("input error, please try again:)")  

print('\nPengkonversian selesai')
print("Mau ngulang konversi? tinggal Run lagi yaa!!")